package:
  name: r-presenceabsence
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.1.9"

source:
  fn: PresenceAbsence_1.1.9.tar.gz
  url: http://cran.r-project.org/src/contrib/PresenceAbsence_1.1.9.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RColorBrewer, rgdal (>= 0.8-7), rgeos (>= 0.2-20), gstat
requirements:
  build:
    - r >=2.2.0
    - r-sp # [not win]

  run:
    - r >=2.2.0
    - r-sp # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sp')" # [not win]
    - "\"%R%\" -e \"library('sp')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://cran.r-project.org/web/packages/PresenceAbsence/
  license: GPL (>= 3)
  summary: This package provides a set of functions useful when evaluating the results of presence-absence models. Package includes functions for calculating threshold dependent measures such as confusion matrices, pcc, sensitivity, specificity, and Kappa, and produces plots of each measure as the threshold is varied. It will calculate optimal threshold choice according to a choice of optimization criteria. It also includes functions to plot the threshold independent ROC curves along with the associated AUC (area under the curve).

# The original CRAN metadata for this package was:

