package:
  name: r-ncdf
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.6.8"

source:
  fn: ncdf_1.6.8.tar.gz
  url: http://cran.r-project.org/src/contrib/ncdf_1.6.8.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RColorBrewer, rgdal (>= 0.8-7), rgeos (>= 0.2-20), gstat
requirements:
  build:
    - r >=2.15.0
    - libnetcdf

  run:
    - r >=2.15.0
    - libnetcdf

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ncdf')" # [not win]
    - "\"%R%\" -e \"library('ncdf')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://cran.r-project.org/web/packages/ncdf/index.html
  license: GPL (>= 3)
  summary: This package provides a high-level R interface to Unidata's netCDF data files, which are portable across platforms and include metadata information in addition to the data sets. Using this package netCDF files can be opened and data sets read in easily. It is also easy to create new netCDF dimensions, variables, and files, or manipulate existing netCDF files. This interface provides considerably more functionality than the old "netCDF" package for R, and is not compatible with the old "netCDF" package for R. 

# The original CRAN metadata for this package was:

