package:
    name: cdat-lite
    version: 5.2rc1

source:
    fn: cdat_lite-5.2rc1.tar.gz
    url: https://pypi.python.org/packages/source/c/cdat-lite/cdat_lite-5.2rc1.tar.gz
    #url: http://ndg.nerc.ac.uk/dist/cdat_lite-5.2-1.tar.gz
    #sha1: 8d7f373367cd05c0378d310ce78ee4a1a68d258b

build:
    number: 2

requirements:
    build:
        - python
        - numpy 1.8.2
        - setuptools
        - libnetcdf
        - hdf5
    run:
        - python
        - numpy 1.8.2
        - libnetcdf
        - hdf5

test:
    imports:
        - cdtime

about:
  home: http://proj.badc.rl.ac.uk/cedaservices/wiki/CdatLite
  summary: A Python package for managing and analysing climate science data.
