package:
    name: netcdf4
    version: {{environ['CBUILD_NETCDF4_VERSION']}}

source:
    git_url: https://github.com/Unidata/netcdf4-python.git
    git_tag: {{environ['CBUILD_NETCDF4_TAG']}}

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - numpy
        - libnetcdf ==4.3.3.1esmf
    run:
        - python
        - setuptools
        - numpy
        - libnetcdf ==4.3.3.1esmf
test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.
