package:
    name: ocgis
    version: {{environ['CBUILD_OCGIS_VERSION']}}

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: {{environ['CBUILD_OCGIS_TAG']}}

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4
        - shapely
        - fiona ==1.4.8
        - gdal ==patch_1.11.1
    run:
        - python
        - numpy
        - netcdf4
        - shapely
        - fiona ==1.4.8
        - gdal ==patch_1.11.1
        - icclim
        - cfunits
        - rtree
        - esmpy =={{environ['CBUILD_OCGIS_ESMF_VERSION']}}
test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: \"OCGIS\" is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.

