package:
    name: icclim
    version: 3.0.0 

source:
    git_url: https://github.com/cerfacs-globc/icclim
    git_tag: master

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4
#        - ctypes

    run:
        - python
        - numpy
        - netcdf4
#        - ctypes

test:
    imports:
        - icclim

    #commands:
    #    -

about:
    home: http://icclim.readthedocs.org/en/latest/
    license: Apache 2.0 License
    summary: Index Calculation CLIMate (ICCLIM) is a Python library for climate indices calculation.
