package:
  name: cfunits
  version: 0.9.6s

source:
  fn: cfunits-0.9.6.tar.gz
  url: http://cfunits-python.googlecode.com/files/cfunits-0.9.6.tar.gz
  md5: e876322cac0d939b5dd9ce53ad708b7e
  patches:
    - migrated_setup_py_to_setuptools_and_fixed_conversion_imports.patch

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - udunits
    - netcdf4 =={{environ['CBUILD_NETCDF4_VERSION']}}

  run:
    - python
    - udunits
    - netcdf4 =={{environ['CBUILD_NETCDF4_VERSION']}}

about:
  home: https://code.google.com/p/cfunits-python/
  license: MIT License
  summary: A Python interface to UNIDATA's Udunits-2 package with CF extensions.

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
