package:
    name: cfchecker
    version: 2.0.6

source:
    fn: cfchecker-2.0.6.tar.gz
    url: https://pypi.python.org/packages/source/c/cfchecker/cfchecker-2.0.6.tar.gz#md5=84dbd1827da00c62f86d45e43ab9a9bd
    #sha1:

build:
    number: 0

    entry_points:
        - cfchecks = cfchecker:cfchecks_main

requirements:
    build:
        - python
        - setuptools
        - cdat-lite
        - udunits
    run:
        - python
        - numpy 1.8.2
        - setuptools
        - cdat-lite
        - udunits

test:
    commands:
        - cfchecks -h
    imports:
        - cfchecker

about:
  home: https://pypi.python.org/pypi/cfchecker
  license: BSD
  summary: The NetCDF Climate Forcast Conventions compliance checker.
