package:
  name: proj4
  version: 4.9.1

source:
  fn: proj-4.9.1.tar.gz
  url: http://download.osgeo.org/proj/proj-4.9.1.tar.gz

build:
  number: 4

about:
  home: http://trac.osgeo.org/proj/
  license: MIT License
  summary: PROJ.4 is a library for performing conversions between cartographic projections.

# vim:set ts=8 sw=2 sts=2 tw=78 et:
